<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (C) 2019 Red Hat, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.jboss</groupId>
    <artifactId>jboss-parent</artifactId>
    <version>53</version>
  </parent>

  <groupId>org.jboss.pnc.deliverablesanalyzer</groupId>
  <artifactId>parent</artifactId>
  <version>2.0.5-SNAPSHOT</version>
  <packaging>pom</packaging>

  <name>Deliverables Analyzer</name>
  <description>Analyzes deliverables.</description>
  <url>https://www.redhat.com/</url>
  <inceptionYear>2019</inceptionYear>
  <organization>
    <name>Red Hat, Inc.</name>
    <url>https://www.redhat.com/</url>
  </organization>

  <licenses>
    <license>
      <name>The Apache Software License, Version 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
      <distribution>repo</distribution>
    </license>
  </licenses>

  <developers>
    <developer>
      <organization>RedHat</organization>
      <organizationUrl>https://www.redhat.com</organizationUrl>
    </developer>
  </developers>

  <modules>
    <module>app</module>
    <module>core</module>
    <module>model</module>
  </modules>

  <scm>
    <connection>scm:git:https://github.com/project-ncl/deliverables-analyzer.git</connection>
    <developerConnection>scm:git:git@github.com:project-ncl/deliverables-analyzer.git</developerConnection>
    <tag>HEAD</tag>
    <url>https://github.com/project-ncl/deliverables-analyzer</url>
  </scm>

  <properties>
    <!-- Maven -->
    <maven.build.timestamp.format>yyyy-MM-dd'T'HH:mm:ss'Z'</maven.build.timestamp.format>
    <maven.compiler.parameters>true</maven.compiler.parameters>
    <maven.compiler.release>21</maven.compiler.release>

    <!-- JDK -->
    <jdk.min.version>21</jdk.min.version>

    <!-- Project -->
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <skipITs>true</skipITs>

    <!-- Quarkus -->
    <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
    <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
    <quarkus.platform.version>3.37.0</quarkus.platform.version>

    <!-- Maven Plugin Versions -->
    <maven.antrun-plugin.version>3.2.0</maven.antrun-plugin.version>
    <maven.buildnumber-plugin.version>3.3.0</maven.buildnumber-plugin.version>
    <maven.clean-plugin.version>3.5.0</maven.clean-plugin.version>
    <maven.compiler-plugin.version>3.15.0</maven.compiler-plugin.version>
    <maven.central-publishing-plugin.version>0.10.0</maven.central-publishing-plugin.version>
    <maven.dependency-plugin.version>3.10.0</maven.dependency-plugin.version>
    <maven.deploy-plugin.version>3.1.4</maven.deploy-plugin.version>
    <maven.enforcer-plugin.version>3.6.2</maven.enforcer-plugin.version>
    <maven.gpg-plugin.version>3.2.8</maven.gpg-plugin.version>
    <maven.install-plugin.version>3.1.4</maven.install-plugin.version>
    <maven.jar-plugin.version>3.5.0</maven.jar-plugin.version>
    <maven.javadoc-plugin.version>3.12.0</maven.javadoc-plugin.version>
    <maven.jxr-plugin.version>3.6.0</maven.jxr-plugin.version>
    <maven.release-plugin.version>3.3.1</maven.release-plugin.version>
    <maven.resources-plugin.version>3.5.0</maven.resources-plugin.version>
    <maven.site-plugin.version>3.21.0</maven.site-plugin.version>
    <maven.source-plugin.version>3.4.0</maven.source-plugin.version>
    <maven.surefire-plugin.version>3.5.6</maven.surefire-plugin.version>

    <!-- Versions PNC -->
    <version.pnc>3.5.8</version.pnc>
    <version.pnc-api>3.5.2</version.pnc-api>
    <version.pnc-common>3.5.4</version.pnc-common>
    <version.pnc-client-auth>1.0.0</version.pnc-client-auth>
    <version.pnc-logging-kafka>3.0.5</version.pnc-logging-kafka>

    <!-- Versions Koji -->
    <version.kojiji>2.25</version.kojiji>
    <version.jhttpc>1.17</version.jhttpc>

    <!-- Versions -->
    <version.commons-vfs2>2.10.0</version.commons-vfs2>
    <version.dkanejs-compose>4.0.0</version.dkanejs-compose>
    <version.spotless>3.4.0</version.spotless>
    <version.ide-config>1.1.0</version.ide-config>
    <version.jandex>3.5.3</version.jandex>
    <version.git-commit-id>10.0.0</version.git-commit-id>
    <version.httpclient5>5.6.3</version.httpclient5>
    <version.lombok>1.18.46</version.lombok>
    <version.maven-core>3.9.16</version.maven-core>
    <version.mycila>5.0.0</version.mycila>
    <version.spdx>2.0.3</version.spdx>
    <version.spotbugs>4.10.2.0</version.spotbugs>
    <version.wiremock>3.13.2</version.wiremock>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>${quarkus.platform.artifact-id}</artifactId>
        <version>${quarkus.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

      <!-- Modules -->
      <dependency>
        <groupId>org.jboss.pnc.deliverablesanalyzer</groupId>
        <artifactId>analyzer-core</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>org.jboss.pnc.deliverablesanalyzer</groupId>
        <artifactId>analyzer-model</artifactId>
        <version>${project.version}</version>
      </dependency>

      <!-- PNC -->
      <dependency>
        <groupId>org.jboss.pnc</groupId>
        <artifactId>dto</artifactId>
        <version>${version.pnc}</version>
        <classifier>jakarta</classifier>
        <exclusions>
          <exclusion>
            <groupId>org.jboss.pnc</groupId>
            <artifactId>pnc-api</artifactId>
          </exclusion>
        </exclusions>
      </dependency>
      <dependency>
        <groupId>org.jboss.pnc</groupId>
        <artifactId>pnc-api</artifactId>
        <version>${version.pnc-api}</version>
        <classifier>jakarta</classifier>
      </dependency>
      <dependency>
        <groupId>org.jboss.pnc</groupId>
        <artifactId>pnc-common</artifactId>
        <version>${version.pnc-common}</version>
        <classifier>jakarta</classifier>
        <exclusions>
          <exclusion>
            <groupId>org.jboss.pnc</groupId>
            <artifactId>pnc-api</artifactId>
          </exclusion>
        </exclusions>
      </dependency>
      <dependency>
        <groupId>org.jboss.pnc</groupId>
        <artifactId>quarkus-pnc-client-auth</artifactId>
        <version>${version.pnc-client-auth}</version>
      </dependency>

      <!-- Koji -->
      <dependency>
        <groupId>com.redhat.red.build</groupId>
        <artifactId>kojiji</artifactId>
        <version>${version.kojiji}</version>
        <exclusions>
          <exclusion>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-templates</artifactId>
          </exclusion>
          <exclusion>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-xml</artifactId>
          </exclusion>
          <exclusion>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy</artifactId>
          </exclusion>
          <exclusion>
            <groupId>org.commonjava.util</groupId>
            <artifactId>jhttpc</artifactId>
          </exclusion>
          <exclusion>
            <groupId>org.slf4j</groupId>
            <artifactId>jcl-over-slf4j</artifactId>
          </exclusion>
          <exclusion>
            <groupId>org.slf4j</groupId>
            <artifactId>log4j-over-slf4j</artifactId>
          </exclusion>
          <exclusion>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
          </exclusion>
          <exclusion>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
          </exclusion>
        </exclusions>
      </dependency>
      <dependency>
        <groupId>org.commonjava.util</groupId>
        <artifactId>jhttpc</artifactId>
        <version>${version.jhttpc}</version>
        <exclusions>
          <exclusion>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcpkix-jdk18on</artifactId>
          </exclusion>
          <exclusion>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk18on</artifactId>
          </exclusion>
          <exclusion>
            <groupId>org.slf4j</groupId>
            <artifactId>jcl-over-slf4j</artifactId>
          </exclusion>
          <exclusion>
            <groupId>org.slf4j</groupId>
            <artifactId>log4j-over-slf4j</artifactId>
          </exclusion>
        </exclusions>
      </dependency>

      <!-- Logging -->
      <dependency>
        <groupId>org.jboss.pnc.logging</groupId>
        <artifactId>quarkus-logging-kafka</artifactId>
        <version>${version.pnc-logging-kafka}</version>
      </dependency>
      <dependency>
        <groupId>org.jboss.pnc.logging</groupId>
        <artifactId>quarkus-logging-kafka-deployment</artifactId>
        <version>${version.pnc-logging-kafka}</version>
      </dependency>

      <!-- Others -->
      <dependency>
        <groupId>org.apache.commons</groupId>
        <artifactId>commons-vfs2</artifactId>
        <version>${version.commons-vfs2}</version>
      </dependency>
      <dependency>
        <groupId>org.apache.httpcomponents.client5</groupId>
        <artifactId>httpclient5</artifactId>
        <version>${version.httpclient5}</version>
        <scope>compile</scope>
      </dependency>
      <dependency>
        <groupId>org.apache.maven</groupId>
        <artifactId>maven-core</artifactId>
        <version>${version.maven-core}</version>
      </dependency>
      <dependency>
        <groupId>org.spdx</groupId>
        <artifactId>java-spdx-library</artifactId>
        <version>${version.spdx}</version>
      </dependency>

      <!-- Lombok -->
      <dependency>
        <groupId>org.projectlombok</groupId>
        <artifactId>lombok</artifactId>
        <version>${version.lombok}</version>
        <scope>provided</scope>
      </dependency>

      <!-- Test -->
      <dependency>
        <groupId>org.wiremock</groupId>
        <artifactId>wiremock</artifactId>
        <version>${version.wiremock}</version>
        <scope>test</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <!-- Cache -->
    <dependency>
      <groupId>org.infinispan.protostream</groupId>
      <artifactId>protostream-processor</artifactId>
      <scope>provided</scope>
    </dependency>

    <!-- Observability -->
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-micrometer-opentelemetry</artifactId>
    </dependency>

    <!-- Logging -->
    <dependency>
      <groupId>org.jboss.pnc.logging</groupId>
      <artifactId>quarkus-logging-kafka</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jboss.pnc.logging</groupId>
      <artifactId>quarkus-logging-kafka-deployment</artifactId>
    </dependency>

    <!-- Test -->
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5-mockito</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.rest-assured</groupId>
      <artifactId>rest-assured</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.awaitility</groupId>
      <artifactId>awaitility</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.wiremock</groupId>
      <artifactId>wiremock</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <repositories>
    <repository>
      <releases>
        <enabled>false</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
      <id>jboss-public-repository</id>
      <name>JBoss Public Maven Repository</name>
      <url>https://repository.jboss.org/nexus/content/groups/public/</url>
    </repository>
    <repository>
      <releases>
        <enabled>false</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
      <id>central-portal-snapshots</id>
      <name>Central Portal Snapshots</name>
      <url>https://central.sonatype.com/repository/maven-snapshots/</url>
    </repository>
  </repositories>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>${quarkus.platform.group-id}</groupId>
          <artifactId>quarkus-maven-plugin</artifactId>
          <version>${quarkus.platform.version}</version>
          <extensions>true</extensions>
          <executions>
            <execution>
              <goals>
                <goal>build</goal>
                <goal>generate-code</goal>
                <goal>generate-code-tests</goal>
                <goal>native-image-agent</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>com.dkanejs.maven.plugins</groupId>
          <artifactId>docker-compose-maven-plugin</artifactId>
          <version>${version.dkanejs-compose}</version>
        </plugin>
        <plugin>
          <groupId>com.github.spotbugs</groupId>
          <artifactId>spotbugs-maven-plugin</artifactId>
          <version>${version.spotbugs}</version>
        </plugin>
        <plugin>
          <groupId>com.mycila</groupId>
          <artifactId>license-maven-plugin</artifactId>
          <version>${version.mycila}</version>
          <configuration>
            <licenseSets>
              <licenseSet>
                <header>./license-header.txt</header>
                <excludes>
                  <exclude>**/README.md</exclude>
                  <exclude>**/LICENSE</exclude>
                  <exclude>**/license-header.txt</exclude>
                  <exclude>**/**.properties</exclude>
                  <exclude>**/build-finder-license-deprecated.json</exclude>
                  <exclude>**/build-finder-license-mapping.json</exclude>
                  <exclude>**/.mvn/**</exclude>
                  <exclude>**/mvnw*</exclude>
                  <exclude>**/openapi.*</exclude>
                  <exclude>.cache/*</exclude>
                  <exclude>.vs*/*</exclude>
                  <exclude>src/main/docker/Dockerfile.jvm</exclude>
                  <exclude>src/main/docker/Dockerfile.native</exclude>
                </excludes>
              </licenseSet>
            </licenseSets>
          </configuration>
          <executions>
            <execution>
              <goals>
                <goal>check</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>com.diffplug.spotless</groupId>
          <artifactId>spotless-maven-plugin</artifactId>
          <version>${version.spotless}</version>
          <configuration>
            <java>
              <removeUnusedImports/>
              <importOrder>
                <file>java-import-order.txt</file>
              </importOrder>
              <eclipse>
                <file>java-formatter.xml</file>
              </eclipse>
              <lineEndings>UNIX</lineEndings>
            </java>
            <pom>
              <sortPom>
                <expandEmptyElements>false</expandEmptyElements>
              </sortPom>
            </pom>
          </configuration>
          <dependencies>
            <dependency>
              <groupId>org.jboss.pnc</groupId>
              <artifactId>ide-config</artifactId>
              <version>${version.ide-config}</version>
            </dependency>
          </dependencies>
          <executions>
            <execution>
              <goals>
                <goal>apply</goal>
              </goals>
              <phase>compile</phase>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-antrun-plugin</artifactId>
          <version>${maven.antrun-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-clean-plugin</artifactId>
          <version>${maven.clean-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>${maven.compiler-plugin.version}</version>
          <configuration>
            <parameters>true</parameters>
            <annotationProcessorPaths>
              <path>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${version.lombok}</version>
              </path>
              <path>
                <groupId>org.infinispan.protostream</groupId>
                <artifactId>protostream-processor</artifactId>
              </path>
            </annotationProcessorPaths>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-dependency-plugin</artifactId>
          <version>${maven.dependency-plugin.version}</version>
          <executions>
            <execution>
              <id>properties</id>
              <goals>
                <goal>properties</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>${maven.deploy-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-enforcer-plugin</artifactId>
          <version>${maven.enforcer-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-failsafe-plugin</artifactId>
          <version>${maven.surefire-plugin.version}</version>
          <configuration>
            <excludedGroups>!integration</excludedGroups>
            <groups>integration</groups>
            <includes>
              <include>**/*Test.java</include>
            </includes>
            <skipITs>${skipITs}</skipITs>
            <systemPropertyVariables>
              <native.image.path>${project.build.directory}/${project.build.finalName}-runner</native.image.path>
              <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
              <maven.home>${maven.home}</maven.home>
            </systemPropertyVariables>
          </configuration>
          <executions>
            <execution>
              <goals>
                <goal>integration-test</goal>
                <goal>verify</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-gpg-plugin</artifactId>
          <version>${maven.gpg-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-install-plugin</artifactId>
          <version>${maven.install-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-jar-plugin</artifactId>
          <version>${maven.jar-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-javadoc-plugin</artifactId>
          <version>${maven.javadoc-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-jxr-plugin</artifactId>
          <version>${maven.jxr-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-release-plugin</artifactId>
          <version>${maven.release-plugin.version}</version>
          <configuration>
            <tagNameFormat>@{project.version}</tagNameFormat>
            <autoVersionSubmodules>true</autoVersionSubmodules>
            <releaseProfiles>gpg-sign,release</releaseProfiles>
            <signTag>false</signTag>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-resources-plugin</artifactId>
          <version>${maven.resources-plugin.version}</version>
          <configuration>
            <propertiesEncoding>UTF-8</propertiesEncoding>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-site-plugin</artifactId>
          <version>${maven.site-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-source-plugin</artifactId>
          <version>${maven.source-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>${maven.surefire-plugin.version}</version>
          <configuration>
            <systemPropertyVariables>
              <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
              <maven.home>${maven.home}</maven.home>
            </systemPropertyVariables>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-surefire-report-plugin</artifactId>
          <version>${maven.surefire-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.sonatype.central</groupId>
          <artifactId>central-publishing-maven-plugin</artifactId>
          <version>${maven.central-publishing-plugin.version}</version>
          <extensions>true</extensions>
          <configuration>
            <!-- as defined in your settings.xml -->
            <publishingServerId>central-publisher</publishingServerId>
          </configuration>
        </plugin>
        <plugin>
          <groupId>io.github.git-commit-id</groupId>
          <artifactId>git-commit-id-maven-plugin</artifactId>
          <version>${version.git-commit-id}</version>
          <configuration>
            <verbose>true</verbose>
          </configuration>
          <executions>
            <execution>
              <goals>
                <goal>revision</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>buildnumber-maven-plugin</artifactId>
          <version>${maven.buildnumber-plugin.version}</version>
          <configuration>
            <doCheck>false</doCheck>
            <doUpdate>false</doUpdate>
            <revisionOnScmFailure>unknown</revisionOnScmFailure>
            <getRevisionOnlyOnce>true</getRevisionOnlyOnce>
            <useLastCommittedRevision>true</useLastCommittedRevision>
          </configuration>
          <executions>
            <execution>
              <goals>
                <goal>create</goal>
              </goals>
              <configuration>
                <shortRevisionLength>8</shortRevisionLength>
                <timestampFormat>{0,date,dd MMMM yyyy}</timestampFormat>
              </configuration>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>io.smallrye</groupId>
          <artifactId>jandex-maven-plugin</artifactId>
          <version>${version.jandex}</version>
          <executions>
            <execution>
              <id>make-index</id>
              <goals>
                <goal>jandex</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
      </plugins>
    </pluginManagement>

    <plugins>
      <plugin>
        <groupId>com.diffplug.spotless</groupId>
        <artifactId>spotless-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-failsafe-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-release-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>buildnumber-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.sonatype.central</groupId>
        <artifactId>central-publishing-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>com.mycila</groupId>
        <artifactId>license-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>io.github.git-commit-id</groupId>
        <artifactId>git-commit-id-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>

  <reporting>
    <plugins>
      <plugin>
        <groupId>com.github.spotbugs</groupId>
        <artifactId>spotbugs-maven-plugin</artifactId>
        <configuration>
          <effort>Max</effort>
          <threshold>Low</threshold>
          <xmlOutput>true</xmlOutput>
          <xmlOutputDirectory>${project.basedir}/target/site</xmlOutputDirectory>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jxr-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-report-plugin</artifactId>
        <configuration>
          <reportsDirectories>
            <reportsDirectory>${project.build.directory}/surefire-reports</reportsDirectory>
            <reportsDirectory>${project.build.directory}/failsafe-reports</reportsDirectory>
          </reportsDirectories>
        </configuration>
      </plugin>
    </plugins>
  </reporting>

  <profiles>
    <profile>
      <id>release</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-source-plugin</artifactId>
            <executions>
              <execution>
                <id>attach-sources</id>
                <goals>
                  <goal>jar-no-fork</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-javadoc-plugin</artifactId>
            <executions>
              <execution>
                <id>attach-javadocs</id>
                <goals>
                  <goal>jar</goal>
                </goals>
                <configuration>
                  <detectOfflineLinks>false</detectOfflineLinks>
                  <quiet>true</quiet>
                  <doclint>none</doclint>
                  <failOnWarnings>false</failOnWarnings>
                  <failOnError>false</failOnError>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>native</id>
      <activation>
        <property>
          <name>native</name>
        </property>
      </activation>
      <properties>
        <quarkus.native.enabled>true</quarkus.native.enabled>
        <skipITs>false</skipITs>
        <quarkus.package.jar.enabled>false</quarkus.package.jar.enabled>
      </properties>
      <build>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-failsafe-plugin</artifactId>
            <version>${maven.surefire-plugin.version}</version>
            <executions>
              <execution>
                <goals>
                  <goal>integration-test</goal>
                  <goal>verify</goal>
                </goals>
                <configuration>
                  <systemPropertyVariables>
                    <native.image.path>${project.build.directory}/${project.artifactId}-runner</native.image.path>
                  </systemPropertyVariables>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
