quarkus.application.name=deliverables-analyzer

quarkus.http.idle-timeout=1H
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=/.*/

quarkus.http.enable-compression=true
quarkus.http.enable-decompression=true

quarkus.shutdown.timeout=30

# KEYCLOAK
%dev.quarkus.keycloak.devservices.enabled=false
%test.quarkus.keycloak.devservices.enabled=false

# OIDC
quarkus.oidc-client.enabled=true
# pnc_client_auth.type=OIDC or LDAP
pnc_client_auth.type=OIDC
# pnc_client_auth.ldap_credentials.path: /mnt/secrets/ldap_credentials # file must be in format: <username>:<password>
%test.quarkus.arc.exclude-types=org.jboss.pnc.quarkus.client.auth.runtime.PNCClientAuthImpl

# LDAP
# required for LDAP1: build-time property
quarkus.http.auth.basic=true

quarkus.security.ldap.enabled=true
quarkus.security.ldap.cache.enabled=true
quarkus.security.ldap.cache.max-age=5m
quarkus.security.ldap.dir-context.url=ldaps://ldap-server.com
quarkus.security.ldap.identity-mapping.search-base-dn=ou=company.com

%test.quarkus.http.auth.basic=false
%test.quarkus.security.ldap.enabled=false

# Packaging
quarkus.package.output-name=deliverables-analyzer
quarkus.package.jar.enabled=true
quarkus.package.jar.type=uber-jar

# Logging
quarkus.log.level=INFO
quarkus.log.category."org.jboss.pnc".level=DEBUG
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n
quarkus.log.handler.kafka.enabled=true
quarkus.log.handler.kafka.broker-list=kafka.example.com:443
quarkus.log.handler.kafka.topic=kafka-topic
quarkus.log.handler.kafka.security-protocol=SSL
quarkus.log.handler.kafka.ssl-truststore-location=/mnt/kafka-client-truststore.jks
quarkus.log.handler.kafka.ssl-truststore-password=none
quarkus.log.handler.kafka.filter-logger-name-pattern=org.jboss.pnc.*
quarkus.log.handler.kafka.level=INFO
%dev.quarkus.log.handler.kafka.enabled=false
%test.quarkus.log.handler.kafka.enabled=false

%dev.quarkus.log.console.json.enabled=false
%test.quarkus.log.console.json.enabled=false

# Openapi
quarkus.smallrye-openapi.info-version=${quarkus.application.version}

# Infinispan
quarkus.infinispan-client.use-schema-registration=false
%dev.quarkus.infinispan-client.username=admin
%dev.quarkus.infinispan-client.password=password
%dev.quarkus.infinispan-client.devservices.image-name=quay.io/infinispan/server:15.0.15.Final
%test.quarkus.infinispan-client.devservices.image-name=quay.io/infinispan/server:15.0.15.Final

# Infinispan Caches
%dev.quarkus.infinispan-client.cache.cancel-events.configuration-resource=/cache/cancel-events-cache.xml
%dev.quarkus.infinispan-client.cache.pnc-archives.configuration-resource=/cache/pnc-archives-cache.xml

# PNC Rest Client
quarkus.rest-client.pnc-api.url=${delan.analyzer.pnc-url}
quarkus.rest-client.pnc-api.read-timeout=30000

# Config
%test.callback.auth.enabled=false
%dev.callback.auth.enabled=false
%test.delan.analyzer.disable-spdx-init=true
%dev.delan.analyzer.disable-koji-lookup=true
